name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/60 * * * *'

jobs:
  scheduled:
    runs-on: [self-hosted, cmmn]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
    - name: prepare branch
      run: |
        git branch -D dogdrip || true
        git checkout --orphan dogdrip
    - name: Run script
      run: |
        npm install
        npm start
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git rm --cached -r .
        git add -f feed.json
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || true
        git push -f origin dogdrip
